kubernetes:
  host: https://kubernetes.default

proxyinjector:
  labels:
    provider: stakater
    group: com.stakater.platform
    version: 0.0.9
  image:
    name: stakater/proxyinjector
    tag: "0.0.9"
    pullPolicy: IfNotPresent
  watchGlobally: true
  configFilePath: /etc/ProxyInjector
  proxyconfig: |-
    enable-default-deny: true
    secure-cookie: false
    verbose: true
    enable-logging: true
    cors-origins:
    - '*'
    cors-methods:
    - GET
    - POST
    resources:
    - uri: '/'